services:
  # Backend API service
  backend:
    build:
      context: ./bmw-api
      dockerfile: Dockerfile
    container_name: bmw-backend
    restart: always
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=development
      - PORT=10000
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - DB_NAME=Web2_2024
      - JWT_SECRET=${JWT_SECRET}

  # Frontend service
  frontend:
    build:
      context: ./BmwApiPt2
      dockerfile: Dockerfile
    container_name: bmw-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
