services:
  # Backend API Service
  - type: web
    name: bmw-backend
    env: docker
    dockerfilePath: ./bmw-api/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_USERNAME
        sync: false  # Set this in Render dashboard
      - key: MONGO_PASSWORD
        sync: false  # Set this in Render dashboard
      - key: JWT_SECRET
        sync: false  # Set this in Render dashboard
      - key: DB_NAME
        value: Web2_2024

  # Frontend Service
  - type: web
    name: bmw-frontend
    env: docker
    dockerfilePath: ./BmwApiPt2/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        fromService:
          name: bmw-backend
          type: web
          property: host
