name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Backend Dependencies
      working-directory: ./bmw-api
      run: npm ci
        
    - name: Run Backend Tests
      working-directory: ./bmw-api
      run: npm test
        
    - name: Install Frontend Dependencies
      working-directory: ./BmwApiPt2
      run: npm ci
        
    - name: Run Frontend Tests
      working-directory: ./BmwApiPt2
      run: npm test -- --watch=false --browsers=ChromeHeadless

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./bmw-api
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/bmw-backend:latest
    
    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./BmwApiPt2
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/bmw-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "accept: application/json" \
          -H "authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
